# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2016-08-08 10:37
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Accessories_sub_category',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=250)),
                ('price', models.IntegerField()),
                ('description', models.TextField()),
                ('photo', models.ImageField(upload_to='')),
                ('name', models.CharField(max_length=250)),
                ('phone_number', models.IntegerField(max_length=10)),
                ('city', models.CharField(max_length=250)),
                ('mobile_accessory_choice_mobile', models.BooleanField()),
                ('mobile_accessory_choice_tablet', models.BooleanField()),
                ('accessory_brand_name', models.CharField(max_length=250)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Bicycles_sub_category',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=250)),
                ('price', models.IntegerField()),
                ('description', models.TextField()),
                ('photo', models.ImageField(upload_to='')),
                ('name', models.CharField(max_length=250)),
                ('phone_number', models.IntegerField(max_length=10)),
                ('city', models.CharField(max_length=250)),
                ('bicycle_brand_name', models.CharField(max_length=250)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Camera_sub_category',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=250)),
                ('price', models.IntegerField()),
                ('description', models.TextField()),
                ('photo', models.ImageField(upload_to='')),
                ('name', models.CharField(max_length=250)),
                ('phone_number', models.IntegerField(max_length=10)),
                ('city', models.CharField(max_length=250)),
                ('camera_item_sub_category', models.CharField(max_length=250)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Cars_sub_category',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=250)),
                ('price', models.IntegerField()),
                ('description', models.TextField()),
                ('photo', models.ImageField(upload_to='')),
                ('name', models.CharField(max_length=250)),
                ('phone_number', models.IntegerField(max_length=10)),
                ('city', models.CharField(max_length=250)),
                ('cars_brand_name', models.CharField(max_length=250)),
                ('cars_model', models.CharField(max_length=250)),
                ('kilometers_driven', models.IntegerField()),
                ('year_manufacture', models.DateField()),
                ('fuel', models.CharField(max_length=250)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Commercial_vehicle_sub_category',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=250)),
                ('price', models.IntegerField()),
                ('description', models.TextField()),
                ('photo', models.ImageField(upload_to='')),
                ('name', models.CharField(max_length=250)),
                ('phone_number', models.IntegerField(max_length=10)),
                ('city', models.CharField(max_length=250)),
                ('commercial_vehicle_brand_name', models.CharField(max_length=250)),
                ('kilometers_driven', models.IntegerField()),
                ('year_manufacture', models.DateField()),
                ('fuel', models.CharField(max_length=250)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Computer_sub_category',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=250)),
                ('price', models.IntegerField()),
                ('description', models.TextField()),
                ('photo', models.ImageField(upload_to='')),
                ('name', models.CharField(max_length=250)),
                ('phone_number', models.IntegerField(max_length=10)),
                ('city', models.CharField(max_length=250)),
                ('computer_item_sub_category', models.CharField(max_length=250)),
                ('computer_brand_name', models.CharField(max_length=250)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Fridge_ac_washingmachine',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=250)),
                ('price', models.IntegerField()),
                ('description', models.TextField()),
                ('photo', models.ImageField(upload_to='')),
                ('name', models.CharField(max_length=250)),
                ('phone_number', models.IntegerField(max_length=10)),
                ('city', models.CharField(max_length=250)),
                ('Fridge_ac_washingmachine_sub_category', models.CharField(max_length=250)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Furniture',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=250)),
                ('price', models.IntegerField()),
                ('furniture_type', models.CharField(max_length=250)),
                ('description', models.TextField()),
                ('photo', models.ImageField(upload_to='')),
                ('name', models.CharField(max_length=250)),
                ('phone_number', models.IntegerField(max_length=10)),
                ('city', models.CharField(max_length=250)),
            ],
        ),
        migrations.CreateModel(
            name='Games_sub_category',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=250)),
                ('price', models.IntegerField()),
                ('description', models.TextField()),
                ('photo', models.ImageField(upload_to='')),
                ('name', models.CharField(max_length=250)),
                ('phone_number', models.IntegerField(max_length=10)),
                ('city', models.CharField(max_length=250)),
                ('Games_item_sub_category', models.CharField(max_length=250)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Kitchen_other',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=250)),
                ('price', models.IntegerField()),
                ('description', models.TextField()),
                ('photo', models.ImageField(upload_to='')),
                ('name', models.CharField(max_length=250)),
                ('phone_number', models.IntegerField(max_length=10)),
                ('city', models.CharField(max_length=250)),
                ('Kitchen_other_sub_category', models.CharField(max_length=250)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Mobiles_sub_category',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=250)),
                ('price', models.IntegerField()),
                ('description', models.TextField()),
                ('photo', models.ImageField(upload_to='')),
                ('name', models.CharField(max_length=250)),
                ('phone_number', models.IntegerField(max_length=10)),
                ('city', models.CharField(max_length=250)),
                ('mobile_brand_name', models.CharField(max_length=250)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Motercycles_sub_category',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=250)),
                ('price', models.IntegerField()),
                ('description', models.TextField()),
                ('photo', models.ImageField(upload_to='')),
                ('name', models.CharField(max_length=250)),
                ('phone_number', models.IntegerField(max_length=10)),
                ('city', models.CharField(max_length=250)),
                ('motorc_brand_name', models.CharField(max_length=250)),
                ('bikes_model', models.CharField(max_length=250)),
                ('kilometers_driven', models.IntegerField()),
                ('year_manufacture', models.DateField()),
                ('fuel', models.CharField(max_length=250)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Other_vehicles_sub_category',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=250)),
                ('price', models.IntegerField()),
                ('description', models.TextField()),
                ('photo', models.ImageField(upload_to='')),
                ('name', models.CharField(max_length=250)),
                ('phone_number', models.IntegerField(max_length=10)),
                ('city', models.CharField(max_length=250)),
                ('Other_vehicles_brand_name', models.CharField(max_length=250)),
                ('kilometers_driven', models.IntegerField()),
                ('year_manufacture', models.DateField()),
                ('fuel', models.CharField(max_length=250)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Spare_parts_bikes_sub_category',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=250)),
                ('price', models.IntegerField()),
                ('description', models.TextField()),
                ('photo', models.ImageField(upload_to='')),
                ('name', models.CharField(max_length=250)),
                ('phone_number', models.IntegerField(max_length=10)),
                ('city', models.CharField(max_length=250)),
                ('spare_bikes_name', models.CharField(max_length=250)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Spare_parts_cars_sub_category',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=250)),
                ('price', models.IntegerField()),
                ('description', models.TextField()),
                ('photo', models.ImageField(upload_to='')),
                ('name', models.CharField(max_length=250)),
                ('phone_number', models.IntegerField(max_length=10)),
                ('city', models.CharField(max_length=250)),
                ('spare_parts_category', models.CharField(max_length=250)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Tablets_sub_category',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=250)),
                ('price', models.IntegerField()),
                ('description', models.TextField()),
                ('photo', models.ImageField(upload_to='')),
                ('name', models.CharField(max_length=250)),
                ('phone_number', models.IntegerField(max_length=10)),
                ('city', models.CharField(max_length=250)),
                ('tablets_brand_name', models.CharField(max_length=250)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Tv_video_sub_category',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=250)),
                ('price', models.IntegerField()),
                ('description', models.TextField()),
                ('photo', models.ImageField(upload_to='')),
                ('name', models.CharField(max_length=250)),
                ('phone_number', models.IntegerField(max_length=10)),
                ('city', models.CharField(max_length=250)),
                ('tv_video_sub_category', models.CharField(max_length=250)),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
