# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2016-08-08 10:39
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appwithmodels', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='accessories_sub_category',
            name='phone_number',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='bicycles_sub_category',
            name='phone_number',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='camera_sub_category',
            name='phone_number',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='cars_sub_category',
            name='phone_number',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='commercial_vehicle_sub_category',
            name='phone_number',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='computer_sub_category',
            name='phone_number',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='fridge_ac_washingmachine',
            name='phone_number',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='furniture',
            name='phone_number',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='games_sub_category',
            name='phone_number',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='kitchen_other',
            name='phone_number',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='mobiles_sub_category',
            name='phone_number',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='motercycles_sub_category',
            name='phone_number',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='other_vehicles_sub_category',
            name='phone_number',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='spare_parts_bikes_sub_category',
            name='phone_number',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='spare_parts_cars_sub_category',
            name='phone_number',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='tablets_sub_category',
            name='phone_number',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='tv_video_sub_category',
            name='phone_number',
            field=models.IntegerField(),
        ),
    ]
