# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2016-08-14 16:11
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appwithmodels', '0002_auto_20160808_1609'),
    ]

    operations = [
        migrations.AddField(
            model_name='cars_sub_category',
            name='categories',
            field=models.CharField(default='cars', max_length=250),
        ),
        migrations.AddField(
            model_name='cars_sub_category',
            name='subcategories',
            field=models.CharField(default='car', max_length=250),
        ),
        migrations.AddField(
            model_name='commercial_vehicle_sub_category',
            name='categories',
            field=models.CharField(default='cars', max_length=250),
        ),
        migrations.AddField(
            model_name='commercial_vehicle_sub_category',
            name='subcategories',
            field=models.CharField(default='car', max_length=250),
        ),
        migrations.AddField(
            model_name='other_vehicles_sub_category',
            name='categories',
            field=models.CharField(default='cars', max_length=250),
        ),
        migrations.AddField(
            model_name='other_vehicles_sub_category',
            name='subcategories',
            field=models.CharField(default='car', max_length=250),
        ),
        migrations.AddField(
            model_name='spare_parts_cars_sub_category',
            name='categories',
            field=models.CharField(default='cars', max_length=250),
        ),
        migrations.AddField(
            model_name='spare_parts_cars_sub_category',
            name='subcategories',
            field=models.CharField(default='car', max_length=250),
        ),
    ]
