# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2016-08-14 16:12
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appwithmodels', '0003_auto_20160814_1611'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cars_sub_category',
            name='year_manufacture',
            field=models.IntegerField(),
        ),
    ]
