# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2016-08-17 16:19
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appwithmodels', '0005_auto_20160816_1234'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Motercycles_sub_category',
            new_name='Motorcycles_sub_category',
        ),
        migrations.RenameField(
            model_name='motorcycles_sub_category',
            old_name='motorc_brand_name',
            new_name='motorcycle_brand_name',
        ),
        migrations.RemoveField(
            model_name='accessories_sub_category',
            name='mobile_accessory_choice_mobile',
        ),
        migrations.RemoveField(
            model_name='accessories_sub_category',
            name='mobile_accessory_choice_tablet',
        ),
        migrations.AddField(
            model_name='accessories_sub_category',
            name='mobile_accessory_choice',
            field=models.CharField(default='mobile', max_length=250),
        ),
    ]
