# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2016-09-12 04:44
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appwithmodels', '0006_auto_20160817_1619'),
    ]

    operations = [
        migrations.AddField(
            model_name='accessories_sub_category',
            name='categories',
            field=models.CharField(default='mobiles', max_length=250),
        ),
        migrations.AddField(
            model_name='accessories_sub_category',
            name='subcategories',
            field=models.CharField(default='mobiles', max_length=250),
        ),
        migrations.AddField(
            model_name='mobiles_sub_category',
            name='categories',
            field=models.CharField(default='mobiles', max_length=250),
        ),
        migrations.AddField(
            model_name='mobiles_sub_category',
            name='subcategories',
            field=models.CharField(default='mobiles', max_length=250),
        ),
        migrations.AddField(
            model_name='tablets_sub_category',
            name='categories',
            field=models.CharField(default='mobiles', max_length=250),
        ),
        migrations.AddField(
            model_name='tablets_sub_category',
            name='subcategories',
            field=models.CharField(default='mobiles', max_length=250),
        ),
    ]
