# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2016-09-12 17:39
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appwithmodels', '0007_auto_20160912_0444'),
    ]

    operations = [
        migrations.AddField(
            model_name='bicycles_sub_category',
            name='categories',
            field=models.CharField(default='motorcycle', max_length=250),
        ),
        migrations.AddField(
            model_name='bicycles_sub_category',
            name='subcategories',
            field=models.CharField(default='bikes', max_length=250),
        ),
        migrations.AddField(
            model_name='camera_sub_category',
            name='categories',
            field=models.CharField(default='electronics', max_length=250),
        ),
        migrations.AddField(
            model_name='camera_sub_category',
            name='subcategories',
            field=models.CharField(default='computer', max_length=250),
        ),
        migrations.AddField(
            model_name='computer_sub_category',
            name='categories',
            field=models.CharField(default='electronics', max_length=250),
        ),
        migrations.AddField(
            model_name='computer_sub_category',
            name='subcategories',
            field=models.CharField(default='computer', max_length=250),
        ),
        migrations.AddField(
            model_name='fridge_ac_washingmachine',
            name='categories',
            field=models.CharField(default='electronics', max_length=250),
        ),
        migrations.AddField(
            model_name='fridge_ac_washingmachine',
            name='subcategories',
            field=models.CharField(default='computer', max_length=250),
        ),
        migrations.AddField(
            model_name='games_sub_category',
            name='categories',
            field=models.CharField(default='electronics', max_length=250),
        ),
        migrations.AddField(
            model_name='games_sub_category',
            name='subcategories',
            field=models.CharField(default='computer', max_length=250),
        ),
        migrations.AddField(
            model_name='kitchen_other',
            name='categories',
            field=models.CharField(default='electronics', max_length=250),
        ),
        migrations.AddField(
            model_name='kitchen_other',
            name='subcategories',
            field=models.CharField(default='computer', max_length=250),
        ),
        migrations.AddField(
            model_name='motorcycles_sub_category',
            name='categories',
            field=models.CharField(default='motorcycle', max_length=250),
        ),
        migrations.AddField(
            model_name='motorcycles_sub_category',
            name='subcategories',
            field=models.CharField(default='bikes', max_length=250),
        ),
        migrations.AddField(
            model_name='spare_parts_bikes_sub_category',
            name='categories',
            field=models.CharField(default='motorcycle', max_length=250),
        ),
        migrations.AddField(
            model_name='spare_parts_bikes_sub_category',
            name='subcategories',
            field=models.CharField(default='bikes', max_length=250),
        ),
        migrations.AddField(
            model_name='tv_video_sub_category',
            name='categories',
            field=models.CharField(default='electronics', max_length=250),
        ),
        migrations.AddField(
            model_name='tv_video_sub_category',
            name='subcategories',
            field=models.CharField(default='computer', max_length=250),
        ),
    ]
