# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2016-09-21 06:35
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appwithmodels', '0008_auto_20160912_1739'),
    ]

    operations = [
        migrations.AlterField(
            model_name='commercial_vehicle_sub_category',
            name='year_manufacture',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='motorcycles_sub_category',
            name='year_manufacture',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='other_vehicles_sub_category',
            name='year_manufacture',
            field=models.IntegerField(),
        ),
    ]
