# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2016-10-15 06:37
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('appwithmodels', '0009_auto_20160921_1205'),
    ]

    operations = [
        migrations.AddField(
            model_name='accessories_sub_category',
            name='created_time',
            field=models.DateTimeField(default=datetime.datetime(2016, 10, 15, 6, 37, 42, 142168, tzinfo=utc)),
        ),
        migrations.AddField(
            model_name='mobiles_sub_category',
            name='created_time',
            field=models.DateTimeField(default=datetime.datetime(2016, 10, 15, 6, 37, 42, 142168, tzinfo=utc)),
        ),
        migrations.AddField(
            model_name='tablets_sub_category',
            name='created_time',
            field=models.DateTimeField(default=datetime.datetime(2016, 10, 15, 6, 37, 42, 142168, tzinfo=utc)),
        ),
    ]
