# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2016-10-15 06:39
from __future__ import unicode_literals

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('appwithmodels', '0012_auto_20161015_0638'),
    ]

    operations = [
        migrations.AlterField(
            model_name='accessories_sub_category',
            name='created_time',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AlterField(
            model_name='mobiles_sub_category',
            name='created_time',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AlterField(
            model_name='tablets_sub_category',
            name='created_time',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
