from django import forms

class Mobile_sub_MobileForm(forms.Form):
    title = forms.CharField(max_length=250)
    price = forms.IntegerField()
    description=forms.CharField(max_length=500)
    photo = forms.ImageField()
    name = forms.CharField(max_length=250)
    phone_number = forms.IntegerField()
    city = forms.CharField(max_length=250)
    mobile_brand_name= forms.ChoiceField(choices=(('s','samsung',('a','apple'))))
    categories=forms.CharField(max_length=250)
    subcategories=forms.CharField(max_length=250)

class Mobile_sub_tablets_form(forms.Form):
    title = forms.CharField(max_length=250)
    price = forms.IntegerField()
    description=forms.CharField(max_length=500)
    photo = forms.ImageField()
    name = forms.CharField(max_length=250)
    phone_number = forms.IntegerField()
    city = forms.CharField(max_length=250)
    tablet_brand_name= forms.ChoiceField(choices=(('sam','samsung'),('app','apple')))
    categories=forms.CharField(max_length=250)
    subcategories=forms.CharField(max_length=250)
    
class Mobile_sub_accessories_form(forms.Form):
    title = forms.CharField(max_length=250)
    price = forms.IntegerField()
    description=forms.CharField(max_length=500)
    photo = forms.ImageField()
    name = forms.CharField(max_length=250)
    phone_number = forms.IntegerField()
    city = forms.CharField(max_length=250)
    mobile_accessory_choice_mobile = forms.BooleanField()
    mobile_accessory_choice_tablet = forms.BooleanField()
    accessory_brand_name =forms.ChoiceField(choices=(('sam','samsung'),('app','apple')))
    categories=forms.CharField(max_length=250)
    subcategories=forms.CharField(max_length=250)


class Computer_sub_category(forms.Form):
    title = forms.CharField(max_length=250)
    price = forms.IntegerField()
    description=forms.CharField(max_length=500)
    photo = forms.ImageField()
    name = forms.CharField(max_length=250)
    phone_number = forms.IntegerField()
    city = forms.CharField(max_length=250)
    computer_item_sub_category= forms.ChoiceField(choices=(('sam','samsung'),('app','apple')))
    computer_brand_name = forms.ChoiceField(choices=(('sam','samsung'),('app','apple')))
    categories=forms.CharField(max_length=250)
    subcategories=forms.CharField(max_length=250)

class Tv_video_sub_category(forms.Form):
   title = forms.CharField(max_length=250)
   price = forms.IntegerField()
   description=forms.CharField(max_length=500)
   photo = forms.ImageField()
   name = forms.CharField(max_length=250)
   phone_number = forms.IntegerField()
   city = forms.CharField(max_length=250)
   tv_video_sub_category=forms.ChoiceField(choices=(('sam','samsung'),('app','apple')))
   categories=forms.CharField(max_length=250)
   subcategories=forms.CharField(max_length=250)

class Camera_sub_category(forms.Form):
    title = forms.CharField(max_length=250)
    price = forms.IntegerField()
    description=forms.CharField(max_length=500)
    photo = forms.ImageField()
    name = forms.CharField(max_length=250)
    phone_number = forms.IntegerField()
    city = forms.CharField(max_length=250)
    camera_item_sub_category=forms.ChoiceField(choices=(('sam','samsung'),('app','apple')))
    categories=forms.CharField(max_length=250)
    subcategories=forms.CharField(max_length=250)

class Games_sub_category(forms.Form):
    title = forms.CharField(max_length=250)
    price = forms.IntegerField()
    description=forms.CharField(max_length=500)
    photo = forms.ImageField()
    name = forms.CharField(max_length=250)
    phone_number = forms.IntegerField()
    city = forms.CharField(max_length=250)
    Games_item_sub_category=forms.ChoiceField(choices=(('sam','samsung'),('app','apple')))
    categories=forms.CharField(max_length=250)
    subcategories=forms.CharField(max_length=250)

class Fridge_ac_washingmachine(forms.Form):
    title = forms.CharField(max_length=250)
    price = forms.IntegerField()
    description=forms.CharField(max_length=500)
    photo = forms.ImageField()
    name = forms.CharField(max_length=250)
    phone_number = forms.IntegerField()
    city = forms.CharField(max_length=250)
    Fridge_ac_washingmachine_sub_category=forms.ChoiceField(choices=(('sam','samsung'),('app','apple')))
    categories=forms.CharField(max_length=250)
    subcategories=forms.CharField(max_length=250)

class Kitchen_other(forms.Form):
    title = forms.CharField(max_length=250)
    price = forms.IntegerField()
    description=forms.CharField(max_length=500)
    photo = forms.ImageField()
    name = forms.CharField(max_length=250)
    phone_number = forms.IntegerField()
    city = forms.CharField(max_length=250)
    Kitchen_other_sub_category=forms.ChoiceField(choices=(('sam','samsung'),('app','apple')))
    categories=forms.CharField(max_length=250)
    subcategories=forms.CharField(max_length=250)

class Cars_sub_category_form(forms.Form):
    title = forms.CharField(max_length=250)
    price = forms.IntegerField()
    description=forms.CharField(max_length=500)
    photo = forms.ImageField()
    name = forms.CharField(max_length=250)
    phone_number = forms.IntegerField()
    city = forms.CharField(max_length=250)
    cars_brand_name = forms.CharField(max_length=250)
    cars_model =forms.CharField(max_length=250)
    kilometers_driven = forms.IntegerField()
    year_manufacture = forms.DateField()
    fuel = forms.CharField(max_length=250)
    categories=forms.CharField(max_length=250)
    subcategories=forms.CharField(max_length=250)
    selector=forms.CharField(max_length=250)

class Commercial_vehicle_sub_category(forms.Form):
    title = forms.CharField(max_length=250)
    price = forms.IntegerField()
    description=forms.CharField(max_length=500)
    photo = forms.ImageField()
    name = forms.CharField(max_length=250)
    phone_number = forms.IntegerField()
    city = forms.CharField(max_length=250)
    commercial_vehicle_brand_name = forms.ChoiceField(choices=(('sam','samsung'),('app','apple')))
    kilometers_driven = forms.IntegerField()
    year_manufacture = forms.DateField()
    fuel = forms.CharField(max_length=250)
    categories=forms.CharField(max_length=250)
    subcategories=forms.CharField(max_length=250)

class Other_vehicles_sub_category(forms.Form):
    title = forms.CharField(max_length=250)
    price = forms.IntegerField()
    description=forms.CharField(max_length=500)
    photo = forms.ImageField()
    name = forms.CharField(max_length=250)
    phone_number = forms.IntegerField()
    city = forms.CharField(max_length=250)
    Other_vehicles_brand_name = forms.CharField(max_length=250)
    kilometers_driven = forms.IntegerField()
    year_manufacture = forms.DateField()
    fuel = forms.CharField(max_length=250)
    categories=forms.CharField(max_length=250)
    subcategories=forms.CharField(max_length=250)  

class Spare_parts_cars_sub_category(forms.Form):
    title = forms.CharField(max_length=250)
    price = forms.IntegerField()
    description=forms.CharField(max_length=500)
    photo = forms.ImageField()
    name = forms.CharField(max_length=250)
    phone_number = forms.IntegerField()
    city = forms.CharField(max_length=250)
    spare_parts_category = forms.ChoiceField(choices=(('sam','samsung'),('app','apple')))
    categories=forms.CharField(max_length=250)
    subcategories=forms.CharField(max_length=250)

class Motercycles_sub_category(forms.Form):
    title = forms.CharField(max_length=250)
    price = forms.IntegerField()
    description=forms.CharField(max_length=500)
    photo = forms.ImageField()
    name = forms.CharField(max_length=250)
    phone_number = forms.IntegerField()
    city = forms.CharField(max_length=250)
    motorc_brand_name = forms.ChoiceField(choices=(('sam','samsung'),('app','apple')))
    bikes_model = forms.CharField(max_length=250)
    kilometers_driven = forms.IntegerField()
    year_manufacture = forms.DateField()
    fuel = forms.CharField(max_length=250)
    categories=forms.CharField(max_length=250)
    subcategories=forms.CharField(max_length=250)

class Bicycles_sub_category(forms.Form):
    title = forms.CharField(max_length=250)
    price = forms.IntegerField()
    description=forms.CharField(max_length=500)
    photo = forms.ImageField()
    name = forms.CharField(max_length=250)
    phone_number = forms.IntegerField()
    city = forms.CharField(max_length=250)
    bicycle_brand_name = forms.ChoiceField(choices=(('sam','samsung'),('app','apple')))
    categories=forms.CharField(max_length=250)
    subcategories=forms.CharField(max_length=250)

class Spare_parts_bikes_sub_category(forms.Form):
    title = forms.CharField(max_length=250)
    price = forms.IntegerField()
    description=forms.CharField(max_length=500)
    photo = forms.ImageField()
    name = forms.CharField(max_length=250)
    phone_number = forms.IntegerField()
    city = forms.CharField(max_length=250)
    spare_bikes_name = forms.CharField(max_length=250)
    categories=forms.CharField(max_length=250)
    subcategories=forms.CharField(max_length=250)

class Furniture(forms.Form):
    title = forms.CharField(max_length=250)
    price = forms.IntegerField()
    furniture_type = forms.CharField(max_length=250)
    description=forms.CharField(max_length=500)
    photo = forms.ImageField()
    name = forms.CharField(max_length=250)
    phone_number = forms.IntegerField()
    city = forms.CharField(max_length=250)
    categories=forms.CharField(max_length=250)
    subcategories=forms.CharField(max_length=250)