from django import forms

class Mobile_sub_MobileForm(forms.Form):
    title = forms.CharField(max_length=250)
    price = forms.IntegerField()
    description=forms.CharField(max_length=500)
    photo = forms.ImageField()
    name = forms.CharField(max_length=250)
    phone_number = forms.IntegerField()
    city = forms.CharField(max_length=250)
    mobile_brand_name= forms.CharField(max_length=250)
    categories=forms.ChoiceField(choices=(('mobiles','mobiles'),('electronics','electronics'),('cars','cars'),('bikes','bikes'),('furniture','furniture')))
    subcategories=forms.ChoiceField(choices=(('mobiles','mobiles'),('tablets','tablets'),('accessories','accessories')))

class Mobile_sub_tablets_form(forms.Form):
    title = forms.CharField(max_length=250)
    price = forms.IntegerField()
    description=forms.CharField(max_length=500)
    photo = forms.ImageField()
    name = forms.CharField(max_length=250)
    phone_number = forms.IntegerField()
    city = forms.CharField(max_length=250)
    tablet_brand_name= forms.CharField(max_length=250)
    categories=forms.ChoiceField(choices=(('mobiles','mobiles'),('electronics','electronics'),('cars','cars'),('bikes','bikes'),('furniture','furniture')))
    subcategories=forms.ChoiceField(choices=(('mobiles','mobiles'),('tablets','tablets'),('accessories','accessories')))
    
class Mobile_sub_accessories_form(forms.Form):
    title = forms.CharField(max_length=250)
    price = forms.IntegerField()
    description=forms.CharField(max_length=500)
    photo = forms.ImageField()
    name = forms.CharField(max_length=250)
    phone_number = forms.IntegerField()
    city = forms.CharField(max_length=250)
    mobile_accessory_choice = forms.CharField(max_length=250)
    accessory_brand_name =forms.CharField(max_length=250)
    categories=forms.ChoiceField(choices=(('mobiles','mobiles'),('electronics','electronics'),('cars','cars'),('bikes','bikes'),('furniture','furniture')))
    subcategories=forms.ChoiceField(choices=(('mobile','mobile'),('tablets','tablets'),('accessories','accessories')))
    


class Computer_sub_category_form(forms.Form):
    title = forms.CharField(max_length=250)
    price = forms.IntegerField()
    description=forms.CharField(max_length=500)
    photo = forms.ImageField()
    name = forms.CharField(max_length=250)
    phone_number = forms.IntegerField()
    city = forms.CharField(max_length=250)
    computer_item_sub_category= forms.CharField(max_length=250)
    computer_brand_name = forms.CharField(max_length=250)
    categories=forms.ChoiceField(choices=(('mobiles','mobiles'),('electronics','electronics'),('cars','cars'),('bikes','bikes'),('furniture','furniture')))
    subcategories=forms.ChoiceField(choices=(('computer','computer'),('tvvideo','tvvideo'),('camera','camera'),('games','games'),('fridge','fridge'),('kitchen','kitchen')))

class Tv_video_sub_category_form(forms.Form):
   title = forms.CharField(max_length=250)
   price = forms.IntegerField()
   description=forms.CharField(max_length=500)
   photo = forms.ImageField()
   name = forms.CharField(max_length=250)
   phone_number = forms.IntegerField()
   city = forms.CharField(max_length=250)
   tv_video_sub_category=forms.CharField(max_length=250)
   categories=forms.ChoiceField(choices=(('mobiles','mobiles'),('electronics','electronics'),('cars','cars'),('bikes','bikes'),('furniture','furniture')))
   subcategories=forms.ChoiceField(choices=(('computer','computer'),('tvvideo','tvvideo'),('camera','camera'),('games','games'),('fridge','fridge'),('kitchen','kitchen')))

class Camera_sub_category_form(forms.Form):
    title = forms.CharField(max_length=250)
    price = forms.IntegerField()
    description=forms.CharField(max_length=500)
    photo = forms.ImageField()
    name = forms.CharField(max_length=250)
    phone_number = forms.IntegerField()
    city = forms.CharField(max_length=250)
    camera_item_sub_category=forms.CharField(max_length=250)
    categories=forms.ChoiceField(choices=(('mobiles','mobiles'),('electronics','electronics'),('cars','cars'),('bikes','bikes'),('furniture','furniture')))
    subcategories=forms.ChoiceField(choices=(('computer','computer'),('tvvideo','tvvideo'),('camera','camera'),('games','games'),('fridge','fridge'),('kitchen','kitchen')))

class Games_sub_category_form(forms.Form):
    title = forms.CharField(max_length=250)
    price = forms.IntegerField()
    description=forms.CharField(max_length=500)
    photo = forms.ImageField()
    name = forms.CharField(max_length=250)
    phone_number = forms.IntegerField()
    city = forms.CharField(max_length=250)
    Games_item_sub_category=forms.CharField(max_length=250)
    categories=forms.ChoiceField(choices=(('mobiles','mobiles'),('electronics','electronics'),('cars','cars'),('bikes','bikes'),('furniture','furniture')))
    subcategories=forms.ChoiceField(choices=(('computer','computer'),('tvvideo','tvvideo'),('camera','camera'),('games','games'),('fridge','fridge'),('kitchen','kitchen')))

class Fridge_ac_washingmachine_form(forms.Form):
    title = forms.CharField(max_length=250)
    price = forms.IntegerField()
    description=forms.CharField(max_length=500)
    photo = forms.ImageField()
    name = forms.CharField(max_length=250)
    phone_number = forms.IntegerField()
    city = forms.CharField(max_length=250)
    Fridge_ac_washingmachine_sub_category=forms.CharField(max_length=250)
    categories=forms.ChoiceField(choices=(('mobiles','mobiles'),('electronics','electronics'),('cars','cars'),('bikes','bikes'),('furniture','furniture')))
    subcategories=forms.ChoiceField(choices=(('computer','computer'),('tvvideo','tvvideo'),('camera','camera'),('games','games'),('fridge','fridge'),('kitchen','kitchen')))

class Kitchen_other_form(forms.Form):
    title = forms.CharField(max_length=250)
    price = forms.IntegerField()
    description=forms.CharField(max_length=500)
    photo = forms.ImageField()
    name = forms.CharField(max_length=250)
    phone_number = forms.IntegerField()
    city = forms.CharField(max_length=250)
    Kitchen_other_sub_category=forms.CharField(max_length=250)
    categories=forms.ChoiceField(choices=(('mobiles','mobiles'),('electronics','electronics'),('cars','cars'),('bikes','bikes'),('furniture','furniture')))
    subcategories=forms.ChoiceField(choices=(('computer','computer'),('tvvideo','tvvideo'),('camera','camera'),('games','games'),('fridge','fridge'),('kitchen','kitchen')))

class Cars_sub_category_form(forms.Form):
    title = forms.CharField(max_length=250)
    price = forms.IntegerField()
    description=forms.CharField(max_length=500)
    photo = forms.ImageField()
    name = forms.CharField(max_length=250)
    phone_number = forms.IntegerField()
    city = forms.CharField(max_length=250)
    cars_brand_name = forms.CharField(max_length=250)
    cars_model =forms.CharField(max_length=250)
    kilometers_driven = forms.IntegerField()
    year_manufacture = forms.IntegerField()
    fuel = forms.ChoiceField(choices=(('petrol','petrol'),('diesel','diesel'),('gas','gas')))
    categories=forms.ChoiceField(choices=(('mobiles','mobiles'),('electronics','electronics'),('cars','cars'),('bikes','bikes'),('furniture','furniture')))
    subcategories=forms.ChoiceField(choices=(('car','car'),('commercial','commercial'),('other','other'),('spare_cars','spare_cars')))

class Commercial_vehicle_sub_category_form(forms.Form):
    title = forms.CharField(max_length=250)
    price = forms.IntegerField()
    description=forms.CharField(max_length=500)
    photo = forms.ImageField()
    name = forms.CharField(max_length=250)
    phone_number = forms.IntegerField()
    city = forms.CharField(max_length=250)
    commercial_vehicle_brand_name = forms.CharField(max_length=250)
    kilometers_driven = forms.IntegerField()
    year_manufacture = forms.IntegerField()
    fuel = forms.ChoiceField(choices=(('petrol','petrol'),('diesel','diesel'),('gas','gas')))
    categories=forms.ChoiceField(choices=(('mobiles','mobiles'),('electronics','electronics'),('cars','cars'),('bikes','bikes'),('furniture','furniture')))
    subcategories=forms.ChoiceField(choices=(('car','car'),('commercial','commercial'),('other','other'),('spare_cars','spare_cars')))
class Other_vehicles_sub_category_form(forms.Form):
    title = forms.CharField(max_length=250)
    price = forms.IntegerField()
    description=forms.CharField(max_length=500)
    photo = forms.ImageField()
    name = forms.CharField(max_length=250)
    phone_number = forms.IntegerField()
    city = forms.CharField(max_length=250)
    Other_vehicles_brand_name = forms.CharField(max_length=250)
    kilometers_driven = forms.IntegerField()
    year_manufacture = forms.DateField()
    fuel = forms.ChoiceField(choices=(('petrol','petrol'),('diesel','diesel'),('gas','gas')))
    categories=forms.ChoiceField(choices=(('mobiles','mobiles'),('electronics','electronics'),('cars','cars'),('bikes','bikes'),('furniture','furniture')))
    subcategories=forms.ChoiceField(choices=(('car','car'),('commercial','commercial'),('other','other'),('spare_cars','spare_cars')))

class Spare_parts_cars_sub_category_form(forms.Form):
    title = forms.CharField(max_length=250)
    price = forms.IntegerField()
    description=forms.CharField(max_length=500)
    photo = forms.ImageField()
    name = forms.CharField(max_length=250)
    phone_number = forms.IntegerField()
    city = forms.CharField(max_length=250)
    fuel = forms.ChoiceField(choices=(('petrol','petrol'),('diesel','diesel'),('gas','gas')))
    categories=forms.ChoiceField(choices=(('mobiles','mobiles'),('electronics','electronics'),('cars','cars'),('bikes','bikes'),('furniture','furniture')))
    subcategories=forms.ChoiceField(choices=(('car','car'),('commercial','commercial'),('other','other'),('spare_cars','spare_cars')))

class Motorcycles_sub_category_form(forms.Form):
    title = forms.CharField(max_length=250)
    price = forms.IntegerField()
    description=forms.CharField(max_length=500)
    photo = forms.ImageField()
    name = forms.CharField(max_length=250)
    phone_number = forms.IntegerField()
    city = forms.CharField(max_length=250)
    motorcycle_brand_name = forms.CharField(max_length=250)
    bikes_model = forms.CharField(max_length=250)
    kilometers_driven = forms.IntegerField()
    year_manufacture = forms.IntegerField()
    fuel = forms.ChoiceField(choices=(('petrol','petrol'),('diesel','diesel'),('gas','gas')))
    categories=forms.ChoiceField(choices=(('mobiles','mobiles'),('electronics','electronics'),('cars','cars'),('bikes','bikes'),('furniture','furniture')))
    subcategories=forms.ChoiceField(choices=(('motorcycle','motorcycle'),('bicycle','bicycle'),('spare_bikes','spare_bikes')))


class Bicycles_sub_category_form(forms.Form):
    title = forms.CharField(max_length=250)
    price = forms.IntegerField()
    description=forms.CharField(max_length=500)
    photo = forms.ImageField()
    name = forms.CharField(max_length=250)
    phone_number = forms.IntegerField()
    city = forms.CharField(max_length=250)
    bicycle_brand_name = forms.CharField(max_length=250)
    categories=forms.ChoiceField(choices=(('mobiles','mobiles'),('electronics','electronics'),('cars','cars'),('bikes','bikes'),('furniture','furniture')))
    subcategories=forms.ChoiceField(choices=(('motorcycle','motorcycle'),('bicycle','bicycle'),('spare_bikes','spare_bikes')))

class Spare_parts_bikes_sub_category_form(forms.Form):
    title = forms.CharField(max_length=250)
    price = forms.IntegerField()
    description=forms.CharField(max_length=500)
    photo = forms.ImageField()
    name = forms.CharField(max_length=250)
    phone_number = forms.IntegerField()
    city = forms.CharField(max_length=250)
    spare_bikes_name = forms.CharField(max_length=250)
    categories=forms.ChoiceField(choices=(('mobiles','mobiles'),('electronics','electronics'),('cars','cars'),('bikes','bikes'),('furniture','furniture')))
    subcategories=forms.ChoiceField(choices=(('motorcycle','motorcycle'),('bicycle','bicycle'),('spare_bikes','spare_bikes')))

class Furniture_Form(forms.Form):
    title = forms.CharField(max_length=250)
    price = forms.IntegerField()
    description=forms.CharField(max_length=500)
    photo = forms.ImageField()
    name = forms.CharField(max_length=250)
    phone_number = forms.IntegerField()
    city = forms.CharField(max_length=250)
    furniture_type = forms.CharField(max_length=250)
    categories=forms.ChoiceField(choices=(('mobiles','mobiles'),('electronics','electronics'),('cars','cars'),('bikes','bikes'),('furniture','furniture')))
    subcategories=forms.ChoiceField(choices=(('furniture','furniture'),('dummyfurniture','dummyfurniture')))
