from django import forms

class Mobile_sub_MobileForm(forms.Form):
    title = forms.CharField(max_length=250)
    price = form.IntegerField()
    description=form.TextField()
    photo = form.ImageField()
    name = form.CharField(max_length=250)
    phone_number = form.IntegerField(max_length=10)
    city = form.CharField(max_length=250)
    mobile_brand_name= forms.ChoiceField(choice=(('s','samsung',('a','apple'))))

class Mobile_sub_tablets_form(forms.Form):
    title = forms.CharField(max_length=250)
    price = form.IntegerField()
    description=form.TextField()
    photo = form.ImageField()
    name = form.CharField(max_length=250)
    phone_number = form.IntegerField(max_length=10)
    city = form.CharField(max_length=250)
    tablet_brand_name= forms.ChoiceField(choice=(('sam','samsung'),('app','apple')))

class Mobile_sub_accessories_form(forms.Form):
    title = forms.CharField(max_length=250)
    price = form.IntegerField()
    description=form.TextField()
    photo = form.ImageField()
    name = form.CharField(max_length=250)
    phone_number = form.IntegerField(max_length=10)
    city = form.CharField(max_length=250)
    mobile_accessory_choice_mobile = form.BooleanField()
    mobile_accessory_choice_tablet = form.BooleanField()
    accessory_brand_name =form.ChoiceField(choice=(('sam','samsung'),('app','apple')))


class Computer_sub_category(forms.Form):
    title = form.CharField(max=250)
    price = form.IntegerField()
    description=form.TextField()
    photo = form.ImageField()
    name = form.CharField(max_length=250)
    phone_number = form.IntegerField(max_value=10)
    city = form.CharField(max=250)
    computer_item_sub_category= forms.ChoiceField(choice=(('sam','samsung'),('app','apple')))
    computer_brand_name = forms.ChoiceField(choice=(('sam','samsung'),('app','apple')))

class Tv_video_sub_category(forms.Form):
   title = form.CharField(max=250)
    price = form.IntegerField()
    description=form.TextField()
    photo = form.ImageField()
    name = form.CharField(max_length=250)
    phone_number = form.IntegerField(max_value=10)
    city = form.CharField(max=250)
    tv_video_sub_category=forms.ChoiceField(choice=(('sam','samsung'),('app','apple')))

class Camera_sub_category(forms.Form):
    title = form.CharField(max=250)
    price = form.IntegerField()
    description=form.TextField()
    photo = form.ImageField()
    name = form.CharField(max_length=250)
    phone_number = form.IntegerField(max_value=10)
    city = form.CharField(max=250)
    camera_item_sub_category=fforms.ChoiceField(choice=(('sam','samsung'),('app','apple')))

class Games_sub_category(forms.Form):
    title = form.CharField(max=250)
    price = form.IntegerField()
    description=form.TextField()
    photo = form.ImageField()
    name = form.CharField(max_length=250)
    phone_number = form.IntegerField(max_value=10)
    city = form.CharField(max=250)
    Games_item_sub_category=forms.ChoiceField(choice=(('sam','samsung'),('app','apple')))

class Fridge_ac_washingmachine(forms.Form):
    title = form.CharField(max=250)
    price = form.IntegerField()
    description=form.TextField()
    photo = form.ImageField()
    name = form.CharField(max_length=250)
    phone_number = form.IntegerField(max_value=10)
    city = form.CharField(max=250)
    Fridge_ac_washingmachine_sub_category=forms.ChoiceField(choice=(('sam','samsung'),('app','apple')))

class Kitchen_other(forms.Form):
    title = form.CharField(max=250)
    price = form.IntegerField()
    description=form.TextField()
    photo = form.ImageField()
    name = form.CharField(max_length=250)
    phone_number = form.IntegerField(max_value=10)
    city = form.CharField(max=250)
    Kitchen_other_sub_category=forms.ChoiceField(choice=(('sam','samsung'),('app','apple')))

class Cars_sub_category(forms.Form):
    title = form.CharField(max=250)
    price = form.IntegerField()
    description=form.TextField()
    photo = form.ImageField()
    name = form.CharField(max_length=250)
    phone_number = form.IntegerField(max_value=10)
    city = form.CharField(max=250)
    cars_brand_name = forms.ChoiceField(choice=(('sam','samsung'),('app','apple')))
    cars_model =forms.ChoiceField(choice=(('sam','samsung'),('app','apple')))
    kilometers_driven = form.IntegerField()
    year_manufacture = form.DateField()
    fuel = form.CharFieldI(max=250)

class Commercial_vehicle_sub_category(forms.Form):
    title = form.CharField(max=250)
    price = form.IntegerField()
    description=form.TextField()
    photo = form.ImageField()
    name = form.CharField(max_length=250)
    phone_number = form.IntegerField(max_value=10)
    city = form.CharField(max=250)
    commercial_vehicle_brand_name = forms.ChoiceField(choice=(('sam','samsung'),('app','apple')))
    kilometers_driven = form.IntegerField()
    year_manufacture = form.DateField()
    fuel = form.CharFieldI(max=250)

class Other_vehicles_sub_category(forms.Form):
    title = form.CharField(max=250)
    price = form.IntegerField()
    description=form.TextField()
    photo = form.ImageField()
    name = form.CharField(max_length=250)
    phone_number = form.IntegerField(max_value=10)
    city = form.CharField(max=250)
    Other_vehicles_brand_name = form.CharField(max=250)
    kilometers_driven = form.IntegerField()
    year_manufacture = form.DateField()
    fuel = form.CharFieldI(max=250)    

class Spare_parts_cars_sub_category(forms.Form):
    title = form.CharField(max=250)
    price = form.IntegerField()
    description=form.TextField()
    photo = form.ImageField()
    name = form.CharField(max_length=250)
    phone_number = form.IntegerField(max_value=10)
    city = form.CharField(max=250)
    spare_parts_category = forms.ChoiceField(choice=(('sam','samsung'),('app','apple')))

class Motercycles_sub_category(forms.Form):
    title = form.CharField(max=250)
    price = form.IntegerField()
    description=form.TextField()
    photo = form.ImageField()
    name = form.CharField(max_length=250)
    phone_number = form.IntegerField(max_value=10)
    city = form.CharField(max=250)
    motorc_brand_name = forms.ChoiceField(choice=(('sam','samsung'),('app','apple')))
    bikes_model = form.CharField(max=250)
    kilometers_driven = form.IntegerField()
    year_manufacture = form.DateField()
    fuel = form.CharFieldI(max=250)

class Bicycles_sub_category(forms.Form):
    title = form.CharField(max=250)
    price = form.IntegerField()
    description=form.TextField()
    photo = form.ImageField()
    name = form.CharField(max_length=250)
    phone_number = form.IntegerField(max_value=10)
    city = form.CharField(max=250)
    bicycle_brand_name = forms.ChoiceField(choice=(('sam','samsung'),('app','apple')))

class Spare_parts_bikes_sub_category(forms.Form):
    title = form.CharField(max=250)
    price = form.IntegerField()
    description=form.TextField()
    photo = form.ImageField()
    name = form.CharField(max_length=250)
    phone_number = form.IntegerField(max_value=10)
    city = form.CharField(max=250)
    spare_bikes_name = form.CharField(max=250)

class Furniture(forms.Form)
    title = form.CharField(max=250)
    price = form.IntegerField()
    furniture_type = form.CharField(max=250)
    description=form.TextField()
    photo = form.ImageField()
    name = form.CharField(max=250)
    phone_number = form.IntegerField(max=10)
    city = form.CharField(max=250)